package com.uniquindio.reporte.model.enums.users;

public enum EnumResidenceCity {
    BOGOTA,
    MEDELLIN,
    CALI,
    BARRANQUILLA,
    CARTAGENA,
    CUCUTA,
    BUCARAMANGA,
    PEREIRA,
    SANTA_MARTA,
    IBAGUE,
    PASTO,
    MANIZALES,
    NEIVA,
    VILLAVICENCIO,
    ARMENIA,
    POPAYAN,
    MONTERIA,
    SINCELEJO,
    VALLEDUPAR,
    FLORENCIA,
    TUNJA,
    QUIBDO,
    RIOHACHA,
    LETICIA,
    SAN_ANDRES,
    YOPAL,
    MOCOA,
    INIRIDA,
    PUERTO_CARREÑO,
    MITU
}
